### ISSUE TITLE
Misc: To Release 1.0.30

### ISSUE THREAD

**Issue by mcuee** [libusb/libusb#1647]
libusb-1.0.29 has been released.
* https://github.com/libusb/libusb/issues/1623

Pending review, may be postponed if not enough reviews:

(Windows)

Let's see if Windows hotplug can make it into libusb 1.0.30 release.
https://github.com/libusb/libusb/pull/1406

https://github.com/libusb/libusb/pull/1512 (new API)
https://github.com/libusb/libusb/pull/1181
https://github.com/libusb/libusb/pull/749
https://github.com/libusb/libusb/pull/1227
https://github.com/libusb/libusb/pull/1018 (libusb0.sys)
https://github.com/libusb/libusb/pull/1127
https://github.com/libusb/libusb/pull/1269
https://github.com/libusb/libusb/pull/1353
https://github.com/libusb/libusb/pull/1323

(macOS)
https://github.com/libusb/libusb/pull/1610
https://github.com/libusb/libusb/issues/1635

(General)
https://github.com/libusb/libusb/pull/1558
https://github.com/libusb/libusb/pull/1550
https://github.com/libusb/libusb/pull/1067
https://github.com/libusb/libusb/issues/890
https://github.com/libusb/libusb/pull/1542
https://github.com/libusb/libusb/pull/1540
https://github.com/libusb/libusb/pull/1461
...

**Comment by mcuee** [comment]
Contributors are welcome to have more regular releases.
* https://github.com/libusb/libusb/discussions/1325

**Comment by ecejeff** [comment]
If you're taking requests from the public, it would be great to merge https://github.com/libusb/libusb/pull/1532. It looks like it's ready to go and is a feature I'd use.

**Comment by mcuee** [comment]
Now we have a new admin @sonatique who is actively working on the project. Hopefully we can get some of the PRs merged and rtelease 1.0.30.

**Comment by Mr-Bossman** [comment]
Thoughts on adding @seanm as an admin too? Continuing discussion here rather than a random pr. https://github.com/libusb/libusb/pull/1508?notification_referrer_id=NT_kwDOAyq0jLQxNTQyNzY2MzE3MTo1MzEzMDM4MA#issuecomment-3220480574

**Comment by mcuee** [comment]
> Thoughts on adding [@seanm](https://github.com/seanm) as an admin too? Continuing discussion here rather than a random pr. [#1508](https://github.com/libusb/libusb/pull/1508)

@seanm 

I just sent you the invitation to join libusb project as an admin. Thanks a lot!

**Comment by seanm** [comment]
> I just sent you the invitation to join libusb project as an admin. Thanks a lot!

Accepted successfully. Thanks.

**Comment by mcuee** [comment]
Great that Windows Hotplug PR has been merged. Thanks a lot to @sonatique for the great work.
* #86 
* #1406

**Comment by mcuee** [comment]
As of now, for the PRs listed for 1.0.30 release, we still have one PR open.
* https://github.com/libusb/libusb/milestone/14

* #1512

@sonatique and @tormodvolden 

Please look at the above PR to see if we want to include it in the 1.0.30 release. Thanks.

**Comment by mcuee** [comment]
Looks like #1512 will be merged soon.

@tormodvolden @sonatique and @seanm 

I am wondering if we should target the 1.0.30 release in about two months time, say by the end of October. 

Currently the target is by end of year 2025. That is okay for me as well. 
* https://github.com/libusb/libusb/milestone/14

**Comment by sonatique** [comment]
> Looks like [#1512](https://github.com/libusb/libusb/pull/1512) will be merged soon.

It's done.
 
> I am wondering if we should target the 1.0.30 release in about two months time, say by the end of October.

I think it would be nice indeed. Does this imply a master freeze starting from now?

I think we should include https://github.com/libusb/libusb/pull/1532 as well, we're close to completion.

**Comment by seanm** [comment]
> Does this imply a master freeze starting from now?

I hope not. We currently have some momentum going, and there are several PRs I'd like to see merged...

**Comment by mcuee** [comment]
Usually we will have one or two RCs before release. No need to freeze so early.

https://github.com/libusb/libusb/releases

Recent releases by @tormodvolden.
1.025-rc1 -->Jan 22, 2022
1.025 release --> Feb 1, 2022

1.026-rc1 -->Mar 28, 2022
1.026 release --> Apr 11, 2022

1.027-rc1 -->Dec 11, 2023
1.027-rc2 --> Jan 28, 2024
1.027 release -->Feb 1, 2024

1.028-rc1 --> Mar 7, 2025
1.028 release --> Mar 19, 2025

1.0.29 release --> Jun 2, 2025 (Special case, no RC)

**Comment by mcuee** [comment]
@sonatique @tormodvolden and @seanm 

Specific to Windows related PR, I think the following PRs are ready for review.

Please take a look. Some of them have been there for quite some time.

* https://github.com/libusb/libusb/pull/1181
* https://github.com/libusb/libusb/pull/1127
* https://github.com/libusb/libusb/pull/1018 (libusb0.sys)
* https://github.com/libusb/libusb/pull/1269
* https://github.com/libusb/libusb/pull/1323

Windows ISOC support is probably still quite broken, especially WinUSB backend. I think the following two PRs may not be ready.
* https://github.com/libusb/libusb/pull/749
* https://github.com/libusb/libusb/pull/1227

Windows ISOC related issues
https://github.com/libusb/libusb/issues?q=is%3Aissue%20state%3Aopen%20label%3Aisoc%20label%3Awindows

Windows related confirmed bugs:
https://github.com/libusb/libusb/issues?q=is%3Aissue%20state%3Aopen%20label%3Abug%20label%3Awindows

**Comment by mcuee** [comment]
@sonatique @tormodvolden and @seanm 

The other long standing PR is for Android. Not so sure if we can do anything about it.
* https://github.com/libusb/libusb/pull/1164

It was the conrinuation of PR #874 
* https://github.com/libusb/libusb/pull/874

Again libusb is quite broken under Android (non rooted device). If we can get #1164 merged (after the rebase and more testing), it is at least not that broken.
https://github.com/libusb/libusb/issues?q=is%3Aissue%20state%3Aopen%20label%3Aandroid

**Comment by mcuee** [comment]
BTW, I am trying to clean the old issues and I may choose to close some issues.

I would also like to close some old PRs but I will ask for permissions before doing that.

Idealy we should have less than 100 issues soon. I hope we will have less than 50 issues and 25 PRs by the end of the year.

**Comment by mcuee** [comment]
New macOS 26 related issue:

* #1661, fixed by PR #1700 
* #1701, need more details,

**Comment by mcuee** [comment]
From @sonatique 
https://github.com/libusb/libusb/issues/1661#issuecomment-3306038303

> I merged PR [#1700](https://github.com/libusb/libusb/pull/1700) . [@mcuee](https://github.com/mcuee) can we close this issue as well?
> 
> [@mcuee](https://github.com/mcuee) [@tormodvolden](https://github.com/tormodvolden) : I am not yet familiar with libusb release process, but we recently released 1.0.29 to fix a bug in 1.0.28 soon after 1.0.28 without RC if I remember correctly.
> 
> Since then, we merged a lot of "heavy" things in master so we may not want to rush for releasing everything, but what about doing a new "maintenance" (it's not "bug fix" this time) release with the content of 1.0.29 + the macOS fix of [#1700](https://github.com/libusb/libusb/pull/1700), maybe even just releasing the macOS binaries. If we do so, are we bound to use 1.0.30 for this maintenance release of can we use 1.0.29.1 or something similar?

**Comment by mcuee** [comment]
My opinion
https://github.com/libusb/libusb/issues/1661#issuecomment-3306225544

> [@sonatique](https://github.com/sonatique)
> 
> I will prefer we release from the git master branch.
> 
> We have never done otherwise.
> 
> Usually we will one RC release and then wait for the testing results in two weeks or one month time for the official release.
> 
> Personally I think we can wait a bit for more macOS related issues to be reported as macOS 26 seems to be a big release which may have more issues. Some of the issues will be fixed by Apple in macOS 26.1. Some of the other issues may require fixes from libusb side.

**Comment by mcuee** [comment]
@sonatique, @tormodvolden and @seanm 

My suggestion is that we still release based on git, if we encounter issues for libusb-1.0.30 release, we can always release 1.0.31 as a bug fixe release.

**Comment by mcuee** [comment]
Work-around for macOS users of #1661 from @mvp, for those who use Homebrew (the most popular package manager for many users of libusb under macOS).

https://github.com/libusb/libusb/issues/1661#issuecomment-3304899172
> When [#1700](https://github.com/libusb/libusb/pull/1700) is merged, it would be possible to fix this on macOS 26 using:
> 
> ```
> brew uninstall libusb --ignore-dependencies
> brew install libusb --head
> ```

**Comment by seanm** [comment]
Would be nice to get these 3 in:

https://github.com/libusb/libusb/pull/1696
https://github.com/libusb/libusb/pull/1686
https://github.com/libusb/libusb/pull/1694

**Comment by mcuee** [comment]
> Would be nice to get these 3 in:
> 
> [#1696](https://github.com/libusb/libusb/pull/1696) [#1686](https://github.com/libusb/libusb/pull/1686) [#1694](https://github.com/libusb/libusb/pull/1694)

I believe #1696 and #1694 should be safe to merge. 

@sonatique Please review the above three issues and merge them if you are fine with the changes. 

After the above three, probably you can tag the 1.0.30-rc1 release.

**Comment by sonatique** [comment]
@seanm @mcuee  I merged #1696 and #1694 . I am a bit reluctant with #1686 because I am the only approver and @tormodvolden has an unresolved discussion.

I never did a release with libusb, are there some explanations somewhere? Thanks.

**Comment by mcuee** [comment]
> [@seanm](https://github.com/seanm) [@mcuee](https://github.com/mcuee) I merged [#1696](https://github.com/libusb/libusb/pull/1696) and [#1694](https://github.com/libusb/libusb/pull/1694) . I am a bit reluctant with [#1686](https://github.com/libusb/libusb/pull/1686) because I am the only approver and [@tormodvolden](https://github.com/tormodvolden) has an unresolved discussion.
> 
> I never did a release with libusb, are there some explanations somewhere? Thanks.

@sonatique 

I agree it is a good idea for @tormodvolden to comment before merging #1686.

As for RC/Release work, please refer to here.
https://github.com/libusb/libusb/wiki/Maintainers'-corner#rcrelease-work

If you have some doubts, feel free to ask and @tormodvolden should be able to help as he has done a few releases.

**Comment by sonatique** [comment]
@mcuee @tormodvolden @seanm : I am sorry I didn't find time yet to try to publish the RC or the next release (and I was waiting for another approval at #1686 as well)

The "user manual" for making a release is quite imposing and contains things and tools I am not familiar with. I understand that it would be good to have somebody else beside @tormodvolden able to release, and I can try, but maybe it would be good if @tormodvolden could handle this once more or we risk to delay the RC and actual release...

**Comment by sonatique** [comment]
@mcuee @seanm @tormodvolden : I started following the steps listed in the maintainers' corner, and some of them are OK, but:
1) I didn't understand what I am supposed to do with libtool versions, sorry I am not familiar with this at all.
2) I didn't really understand how the actual release builds (archive) are made. Am I supposed to build them locally with MinGW32? Or use github? The wiki mention running make distcheck, but I am not sure it this is following the second point that say to use MinGW32 or not. I get compilation failure when doing so and it feel weird. Is this supposed to build the Window binaries archive as well? What about 64bit?
3) We don't create release archives for MacOS (darwin) right?
4) I don't have the required access right for  https://sourceforge.net/projects/libusb/files/releases (OK this is not for RC, but though)

Sorry if these are trivial questions, any help appreciated, thanks

**Comment by tormodvolden** [comment]
Hi sonatique, I can help out with the release technical details. I understand we want to do an RC soon.

Can you please draft release notes, and if there is any special that needs mentioning in the announcement? And can everybody help out testing and report what has been tested? And by testing I mean on real hardware with real applications. Especially the last part is a big part of the work with libusb releases. Has it been verified that all new functions or other API changes are properly documented in doxygen?

If you plan to roll up a release yourself in the future, please start by adding your signing keys to the KEYS file, and for the trust building, do this as early as possible.

Yes, the libtool versioning rules are complicated, there should be a reference, or at least it has been mentioned in commits changing this. The proper release (source) is made with distcheck. We don't publish build for macOS any longer, since homebrew picks it up very quickly.

**Comment by mcuee** [comment]
@sonatique 

Example test matrix for part RC releases.

1.0.28-rc1
* https://github.com/libusb/libusb/issues/1615

1.0.27-rc1
* https://github.com/libusb/libusb/issues/1372

1.0.26-rc1
* https://github.com/libusb/libusb/issues/1099

1.0.25-rc1
* https://github.com/libusb/libusb/issues/1046

**Comment by mcuee** [comment]
> I don't have the required access right for https://sourceforge.net/projects/libusb/files/releases (OK this is not for RC, but though)

@sonatique and @seanm 

Please help to give me the Sourceforge user name and I can add you to the admin team.

**Comment by mcuee** [comment]
FYI, for libusb-win32 project, only the mailing list function is used now. All other functions have been moved to github.

But for libusb project, probably we still want to keep it for both the mailing list function and the file download function.

**Comment by mcuee** [comment]
BTW, I just corrected one mistake in Sourceforge, somehow the default download is wrong.

<img width="1036" height="137" alt="Image" src="https://github.com/user-attachments/assets/af891a58-8cf5-49bc-8b33-f6111557fea8" />

Now it is fixed.

<img width="1048" height="136" alt="Image" src="https://github.com/user-attachments/assets/58965780-1236-4734-b733-8d2e85386d83" />

**Comment by mcuee** [comment]
BTW, somehow most of the download for libusb-compat-0.1 is still the old version. I have uploaded the three later versions on 21-Oct-2023.

<img width="1362" height="365" alt="Image" src="https://github.com/user-attachments/assets/afedf3a3-1bf0-4a12-b1bc-d7e2cc213b0b" />

**Comment by seanm** [comment]
> Please help to give me the Sourceforge user name and I can add you to the admin team.

I am https://sourceforge.net/u/sean_mcbride/profile

**Comment by sonatique** [comment]
@tormodvolden @mcuee : thanks. I'll be able to work on this starting October 28.

**Comment by sonatique** [comment]
> [@sonatique](https://github.com/sonatique) and [@seanm](https://github.com/seanm)
> Please help to give me the Sourceforge user name and I can add you to the admin team.

I am https://sourceforge.net/u/sonatique/profile

**Comment by mvp** [comment]
Any chance to have libusb 1.0.30 released before New Year?

**Comment by seanm** [comment]
I've just looked over the commits since last release and made release notes: https://github.com/libusb/libusb/pull/1724

**Comment by tormodvolden** [comment]
As mentioned above I can help out with the release "mechanics" (the release checklist and binaries etc) but I won't be able to do much testing and QA. Maybe someone can start a test matrix https://github.com/libusb/libusb/issues/1647#issuecomment-3399883403 ? That is, of course, if we agree that we are in testing freeze now.

**Comment by mcuee** [comment]
> As mentioned above I can help out with the release "mechanics" (the release checklist and binaries etc) but I won't be able to do much testing and QA. Maybe someone can start a test matrix [#1647 (comment)](https://github.com/libusb/libusb/issues/1647#issuecomment-3399883403) ? That is, of course, if we agree that we are in testing freeze now.

I think we can have a freeze now.

**Comment by mcuee** [comment]
> I am https://sourceforge.net/u/sonatique/profile

Done. I have added you to the Sourceforge libusb project as an admin.

**Comment by mcuee** [comment]
@sonatique, @seanm and @tormodvolden 

I think we can have a freeze and then have an RC1 of libusb-1.0.30 soon.

**Comment by mcuee** [comment]
> > Please help to give me the Sourceforge user name and I can add you to the admin team.
> 
> I am https://sourceforge.net/u/sean_mcbride/profile

Done. I have added you as an admin.

**Comment by sonatique** [comment]
@tormodvolden 
> please start by adding your signing keys to the KEYS file, and for the trust building, do this as early as possible.

Does this looks ok: https://github.com/libusb/libusb/commit/01647138951e1d44dd97f1eb1a1b5a6a44bd8773 ?

**Comment by mvp** [comment]
I hate to be that guy, but where we are on 1.0.30 release? My utility uhubctl is still broken on macOS 26+ unless users manually build libusb from master branch...

**Comment by seanm** [comment]
@mvp the libusb project, like many open source projects, has very little manpower behind it.  It seems the people with some time (like me), don't know how to do a release; and the people that know how to do a release don't seem to have time. And so here we are.

**Comment by mvp** [comment]
@seanm, I totally understand. Just was wondering if anything is happening for the release, and perhaps how I can help.

**Comment by mcuee** [comment]
> [@seanm](https://github.com/seanm), I totally understand. Just was wondering if anything is happening for the release, and perhaps how I can help.

One potential way is to join libusb project as we are short of resources.

**Comment by mcuee** [comment]
As mentioned here, contributors are welcome to have more regular release.
* https://github.com/libusb/libusb/discussions/1325

**Comment by tormodvolden** [comment]
> As mentioned above I can help out with the release "mechanics" (the release checklist and binaries etc) but I won't be able to do much testing and QA. Maybe someone can start a test matrix [#1647 (comment)](https://github.com/libusb/libusb/issues/1647#issuecomment-3399883403) ? That is, of course, if we agree that we are in testing freeze now.

Again, I can do the release process but I cannot do much of the testing. We need as much as possible of testing of real applications on real hardware. This is something that anyone can help out with. Preferably we make a freeze so that I can make a Release Candidate for testing. Are there any issues that must be fixed before release (that would be for instance a notable regression from previous release, or something wrong in a new API)?

**Comment by seanm** [comment]
> Again, I can do the release process 

Please do so then.

>We need as much as possible of testing of real applications on real hardware. This is something that anyone can help out with.

People are constantly testing master.

>Preferably we make a freeze so that I can make a Release Candidate for testing.

We've been frozen for weeks. Only tiny things have been merged. Only 3 commits since September.

>Are there any issues that must be fixed before release (that would be for instance a notable regression from previous release, or something wrong in a new API)?

Not that I know of.

**Comment by mcuee** [comment]
Once PR #1755 is merged, we will have 1.0.30-rc1.
* #1755 

Then we can probably go through about two weeks of RC1 testing phase to see if there are major issues (newly introduced or regression). If no then we are good to go with 1.0.30 release.

**Comment by tormodvolden** [comment]
The 1.0.30-rc1 has been released: https://sourceforge.net/p/libusb/mailman/message/59300066/
Please post test results to #1757

**Comment by mcuee** [comment]
> Just was wondering if anything is happening for the release, and perhaps how I can help.

@mvp 

Just wondering if you can carry out some testing on libusb-1.0.31rc1 if you have some time. Thanks.

**Comment by mcuee** [comment]
Looks like we are more or less ready now for the 1.0.30 release.

Pending PRs to review.

* #1680
* #1695
* #1774
* #1775
* #1776
* #1782 (delay to 1.0.31 as per @seanm)

Some of them can probably be delayed as well if deemed not ready or not so important for 1.0.30 release.

**Comment by mcuee** [comment]
@tormodvolden, @sonatique and @seanm 

My take on the pending PRs for 1.0.30 release.

* https://github.com/libusb/libusb/pull/1680 (good to merge for macOS)
* https://github.com/libusb/libusb/pull/1695 (good to merge for macOS). Take note @hjelmn has reviwed it.
* https://github.com/libusb/libusb/pull/1774 (delay to 1.0.31)
* https://github.com/libusb/libusb/pull/1775 (good to merge for WebAssembly)
* https://github.com/libusb/libusb/pull/1776 (delay to 1.0.31)
* https://github.com/libusb/libusb/pull/1782 (delay to 1.0.31 as per @seanm)
* https://github.com/libusb/libusb/pull/1783 (not related to codes, good to merge)
* https://github.com/libusb/libusb/pull/1784 (delay to 1.0.31)
* https://github.com/libusb/libusb/pull/1785 (good to merge for Windows and other platforms)
* https://github.com/libusb/libusb/pull/1658 (delay to 1.0.31)

But I am okay with any decisions.

**Comment by mcuee** [comment]
@tormodvolden, @sonatique and @seanm 

I am thinking we should move on and release 1.0.30 soon. 

IMHO we can just merge PR #1783 and go.

* https://github.com/libusb/libusb/pull/1680 (good to merge for macOS, but can be delayed as well)
* https://github.com/libusb/libusb/pull/1695 (good to merge for macOS, but can be delayed as well). Take note @hjelmn has reviwed it.
* https://github.com/libusb/libusb/pull/1774 (delay to 1.0.31)
* https://github.com/libusb/libusb/pull/1776 (delay to 1.0.31)
* https://github.com/libusb/libusb/pull/1782 (delay to 1.0.31 as per @seanm)
* https://github.com/libusb/libusb/pull/1783 (not related to codes, good to merge)
* https://github.com/libusb/libusb/pull/1784 (delay to 1.0.31)
* https://github.com/libusb/libusb/pull/1658 (delay to 1.0.31)

**Comment by seanm** [comment]
We have been talking about having a release for many months now. My vote is to just release master as is.

**Comment by mcuee** [comment]
> We have been talking about having a release for many months now. My vote is to just release master as is.

I am fine with the proposal.

@tormodvolden and @sonatique 

Any objections?

**Comment by tormodvolden** [comment]
Hi, I am back from vacations. I will make the release this week, latest in the weekend. I will look at the above lists of suggested PRs, but I agree we should defer most changes to after the release.

**Comment by sonatique** [comment]
> > We have been talking about having a release for many months now. My vote is to just release master as is.
> 
> I am fine with the proposal.
> 
> [@tormodvolden](https://github.com/tormodvolden) and [@sonatique](https://github.com/sonatique)
> 
> Any objections?

I am good for releasing. Thank you @mcuee for the extensive testing!

As for merging https://github.com/libusb/libusb/pull/1783 : I am OK as well. Would you like me to do it now?

**Comment by mcuee** [comment]
> As for merging [#1783](https://github.com/libusb/libusb/pull/1783) : I am OK as well. Would you like me to do it now?

Yes, please merge this PR. Thanks.

Edit: merged by Tormod.

**Comment by mcuee** [comment]
As Issue https://github.com/libusb/libusb/issues/1794 is a regression, I have added https://github.com/libusb/libusb/issues/1794 and https://github.com/libusb/libusb/pull/1796 to milestone 1.0.30.

* #1794 
* #1796

**Comment by mcuee** [comment]
* https://github.com/libusb/libusb/pull/1679#issuecomment-4232806567

> we hit a few issues in Darwin recently, I think we should consider resurrecting, fixing and merging this one ASAP, as well as https://github.com/libusb/libusb/pull/1695

I agree.

@sonatique 

I have added the following issues to 1.0.30 milestone. Feel free to change.
* #1695 -- merged
* #1795 

Edit: I have removed #1679 and #1680 as #1679 is not ready.

**Comment by mcuee** [comment]
@sonatique @seanm and @tormodvolden 

Issue #1813 and the associated PR #1814 may be worth looking at before 1.0.30 release.
* #1813 
* #1814

**Comment by mcuee** [comment]
@tormodvolden @seanm and @sonatique 

I think we are ready for 1.0.30 release, right?

**Comment by tormodvolden** [comment]
Especially now with #1795 being merged, I think we have finished everything considered for 1.0.30. There have been a lot of activity lately and many changes since the RC. Also some important enough issue came up just when I wanted to prepare the release. It looks to me we should make a short RC2, since there have been changes all around, touching all major platforms. I will start preparing this, so please tell you don't agree or I have missed something.

**Comment by mcuee** [comment]
> Especially now with [#1795](https://github.com/libusb/libusb/pull/1795) being merged, I think we have finished everything considered for 1.0.30. There have been a lot of activity lately and many changes since the RC. Also some important enough issue came up just when I wanted to prepare the release. It looks to me we should make a short RC2, since there have been changes all around, touching all major platforms. I will start preparing this, so please tell you don't agree or I have missed something.

No objections here. We may want to have two weeks between RC2 and final release if no new critial issues pop-up.

**Comment by tormodvolden** [comment]
The RC2 has been released and please use #1824 to report any relevant issues.

**Comment by mcuee** [comment]
It seems to me that we are more or less ready for libusb-1.0.30 release.

Hopefully more users can report the success or issues for the 1.0.30-rc2.
* https://github.com/libusb/libusb/issues/1824

**Comment by tormodvolden** [comment]
v1.0.30 has been released: https://sourceforge.net/p/libusb/mailman/message/59335553/
